import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INGREDIENTS_FILE_PATH = os.path.join(BASE_DIR, "data", "ingredients.csv")
TAGS_FILE_PATH = os.path.join(BASE_DIR, "data", "tags.json")
MIN_AMOUNT = 1
MAX_AMOUNT = 32000
MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 1440
DEFAULT_PAGE_SIZE = 6
MAX_PAGE_SIZE = 100
MAX_LENGHT_EMAIL = 254
MAX_LENGHT_FIRST_NAME = 150
MAX_LENGHT_NAME = 200
MAX_LENGHT_SLUG = 200
DEFAULT_EXTRA_FORMS = 1
MIN_REQUIRED_FORMS = 1
SAFE_METHODS = ('GET', 'HEAD', 'OPTIONS')
